debug: false  # ??? ??? ??? ??? ? ?? ??? ?? ??
management.endpoints.web.exposure.include: "*"  # actuator ? endpoint? ?? ???? ??

logging:
  level:
    bitstudy.board: debug # ?? ?????? ?? debug??? ??
    org.springframework.web.servlet: debug  # servlet ??? ??? ?????
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # jpa ??? ??? ?? ??? ???? ??? ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: leeyoungkyu
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true # test? ?????? ???? ??? ? ?? ??? (??? data.sql??? ?? ?? ? ?????? ????)
    hibernate.ddl-auto: create  #??? ?? ? ???? ??? ?? ?? ? DDL ??
    show-sql: true # ??? ?? sql ?? ??
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always  # data.sql? ?? ????? ????